/**
 * fonts/*.woff2 를 base64로 styles.css의 마커 구간에 내장한다.
 * 이렇게 하면 플러그인 3파일(main.js/manifest.json/styles.css)만으로
 * 오프라인에서도 손글씨·판타지 폰트가 동일하게 렌더된다.
 */
import { readFileSync, writeFileSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

const fonts = [
  { family: "FMS Serif", file: "fonts/cinzel.woff2", weight: 600 },   // 라틴 장식 (격자·나침반)
  { family: "FMS Hand", file: "fonts/gaegu-ko.woff2", weight: 400 },  // 한글+라틴 손글씨 (지명·메모)
];

let css = "/* FONTS-START (generated by scripts/embed-fonts.mjs — do not edit) */\n";
for (const f of fonts) {
  const b64 = readFileSync(join(root, f.file)).toString("base64");
  css += `@font-face{font-family:"${f.family}";font-style:normal;font-weight:${f.weight};` +
    `font-display:swap;src:url(data:font/woff2;base64,${b64}) format("woff2");}\n`;
}
css += "/* FONTS-END */";

const stylesPath = join(root, "styles.css");
let styles = readFileSync(stylesPath, "utf8");
const startRe = /\/\* FONTS-START[\s\S]*?\/\* FONTS-END \*\//;
if (startRe.test(styles)) {
  styles = styles.replace(startRe, css);
} else {
  styles = css + "\n\n" + styles;
}
writeFileSync(stylesPath, styles);
console.log(`Embedded ${fonts.length} fonts into styles.css (+${Math.round(css.length / 1024)}KB)`);
