/**
 * Embeds fonts/*.woff2 as base64 into the marked section of styles.css.
 * This way the three plugin files (main.js/manifest.json/styles.css) alone render
 * the handwriting and fantasy fonts identically, even offline.
 */
import { readFileSync, writeFileSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

const fonts = [
  { family: "FMS Serif", file: "fonts/cinzel.woff2", weight: 600 },   // decorative Latin (grid, compass)
  { family: "FMS Hand", file: "fonts/gaegu-ko.woff2", weight: 400 },  // Hangul + Latin handwriting (place names, notes)
];

let css = "/* FONTS-START (generated by scripts/embed-fonts.mjs — do not edit) */\n";
for (const f of fonts) {
  const b64 = readFileSync(join(root, f.file)).toString("base64");
  css += `@font-face{font-family:"${f.family}";font-style:normal;font-weight:${f.weight};` +
    `font-display:swap;src:url(data:font/woff2;base64,${b64}) format("woff2");}\n`;
}
css += "/* FONTS-END */";

const stylesPath = join(root, "styles.css");
let styles = readFileSync(stylesPath, "utf8");
const startRe = /\/\* FONTS-START[\s\S]*?\/\* FONTS-END \*\//;
if (startRe.test(styles)) {
  styles = styles.replace(startRe, css);
} else {
  styles = css + "\n\n" + styles;
}
writeFileSync(stylesPath, styles);
console.log(`Embedded ${fonts.length} fonts into styles.css (+${Math.round(css.length / 1024)}KB)`);
